# Generated by Django 3.2 on 2022-09-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
